" start up pathogen
filetype off
execute pathogen#runtime_append_all_bundles()
execute pathogen#helptags()

" Prevent vim from emulating the original vi's bugs and limitations
set nocompatible

" set indenting options
set autoindent
set smartindent

" tab options
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab

" won't beep at you, instead screen flashes
set vb t_vb=

" removes highlighting of searches
set nohls

" syntax highlighting
syntax on
filetype on
filetype plugin indent on

" make backup files
set backup
set backupdir=~/.vim/backup

" share windows clipboard
" set clipboard

" set swap directory
set directory=~/.vim/tmp

" file formats to support in order
set fileformats=unix,dos,mac

" set line numbers on
set number
set numberwidth=5 " good up to 99999 lines

" set spellcheck for specified file formats
au BufRead,BufNewFile *.tex,*.txt set spell

" set colorscheme and background
set background=dark
colorscheme blackboard 

" so makefiles use hard tab
autocmd FileType make set noexpandtab

" python stuff
set foldmethod=indent
set foldlevel=99

" Pyflakes 
" let g:pyflakes_use_quickfix = 0

" Pep8 testing of code
let g:pep8_map='<leader>8'
au FileType python set omnifunc=pythoncomplete#Complete

" SuperTab
let g:SuperTabDefaultCompletionType = "context"
set completeopt=menuone,longest,preview

" NERD Tree
map <leader>n :NERDTreeToggle<CR>

" Ropevim
map <leader>j :RopeGotoDefinition<CR>
map <leader>r :RopeRename<CR>

" Ack Searching
nmap <leader>a <Esc>:Ack!

" Move windows with control and edit directions
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" Mapping fix for TaskList
map <leader>td <Plug>TaskList

" Gundo Plugin
map <leader>g :GundoToggle<CR>
