if [ -r /etc/profile ] ; then
. /etc/profile
fi

#autoload the functions
fpath=(/etc/zsh/ $fpath)
autoload precmd dircolors

DISPLAY=:0

#shell functions
setenv(){export $1=$2} #csh compatibility

#setup backspace correctly
stty erase '^?'

#delete key
bindkey '\e[3~' delete-char

#home
bindkey '\e[1~' beginning-of-line
#end
bindkey '\e[4~' end-of-line

#insert
bindkey '\e[2~' overwrite-mode

#tab completion
bindkey '^i' expand-or-complete-prefix


## zsh specific options
setopt NOBGNICE

setopt PROMPT_SUBST

# %1 killed. will show up exactly when it is killed
setopt interactivecomments
unsetopt flowcontrol


# Lines configured by zsh-newuser-install
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/sean/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

#vars used by zsh
export EDITOR="vim"

# aliases
alias ls='ls --color'
alias ll='ls -l'
alias la='ls -a'
alias inv='ls --color'
alias fileinfo='wc -lwc'
alias ssh='ssh -c arcfour -Y'
alias scp='scp -c arcfour -pr'
alias grep='grep -Hn --color'

# path setup
PATH=$PATH:~/.vim/bundle/syntastic/syntax_checkers/python

#{{{ History Stuff
# Where it gets saved
HISTFILE=~/.history

# Remember about a years worth of history (AWESOME)
SAVEHIST=10000
HISTSIZE=10000

# Don't overwrite, append!
setopt APPEND_HISTORY

# Write after each command
# setopt INC_APPEND_HISTORY

# Killer: share history between multiple shells
setopt SHARE_HISTORY

# If I type cd and then cd again, only save the last one
setopt HIST_IGNORE_DUPS

# Even if there are commands inbetween commands that are the same, still only save the last one
setopt HIST_IGNORE_ALL_DUPS

# Pretty    Obvious.  Right?
setopt HIST_REDUCE_BLANKS

# If a line starts with a space, don't save it.
setopt HIST_IGNORE_SPACE
setopt HIST_NO_STORE

# When using a hist thing, make a newline show the change before executing it.
setopt HIST_VERIFY

# Save the time and how long a command ran
setopt EXTENDED_HISTORY

setopt HIST_SAVE_NO_DUPS
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS
#}}}
